# Generated by Django 4.1.7 on 2023-07-10 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_remove_orderproduct_item_orderproduct_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='saved',
            field=models.ManyToManyField(related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
