# Generated by Django 4.1.7 on 2023-08-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_status_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default='user.png', upload_to=''),
        ),
    ]
